image: vakz:java-8-with-aws-eb

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: ./gradlew assemble

test:
  stage: test
  script:
    - export JAVA_OPTS=-Dfile.encoding=UTF-8
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - ./gradlew shadowJar
    - apt-get update -qq && apt-get install -y -qq python-pip
    - pip install awsebcli
    - eb deploy Redditprofiler-group
  only:
    - master