image: openjdk:8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: ./gradlew build

test:
  stage: test
  script:
    - export JAVA_OPTS=-Dfile.encoding=UTF-8
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - ./gradlew shadowJar
    - apt-get install -y py-pip
    - pip install awsebcli
    - eb deploy
  only:
    - master